# Generated by Django 3.2.5 on 2021-07-04 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chat_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
