# Generated by Django 3.2.5 on 2021-07-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210704_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='chat_id',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
